name: PR build test

on:
  pull_request_target:

jobs:
  build:
    uses: ndechesne/meta-qcom/.github/workflows/premerge-template.yml@master
    with:
      host: ubuntu-20.04
      images: core-image-base core-image-weston core-image-x11 initramfs-test-image initramfs-test-full-image cryptodev-module
      machines: >-
        ['dragonboard-410c', 'qcom-armv8a', 'sdx55-mtp']
    secrets: inherit
